# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_sim <- function(interaction, data, isFactor) {
    .Call('RIT_compute_sim', PACKAGE = 'RIT', interaction, data, isFactor)
}

cpp_Relaxed_RIT <- function(datas, theta, factor, epsilon_cont, epsilon_cat, n_trees, depth, branch, min_inter_sz, es) {
    .Call('RIT_cpp_Relaxed_RIT', PACKAGE = 'RIT', datas, theta, factor, epsilon_cont, epsilon_cat, n_trees, depth, branch, min_inter_sz, es)
}

